<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Lab1</title>
	<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link rel="stylesheet" type="text/css" href="css/responsive.css">
</head>
<body>
	<div class="container-fluid px-0">

		<h1 class="my-4">Lab 1</h1>

		<!-- ******************************************************************************************************** *****************************      QUESTION 1 - STUDENT GRADE  ************************************************************************************************************************************************** -->
			<h2 class="mb-5 pb-2 w-100" style="background-color: #03071E; color: white;"
			data-bs-toggle="collapse" href="#question1" role="button"
			aria-expanded="false" aria-controls="question1">Question 1
			<br> <span style="font-size: 24px;">Student Grade</span></h2>

			<div class="container"> <div class="collapse p-4 my-4" id="question1">

				<?php
				if (isset($_POST['submit1'])) {
					$quiz = (int)$_POST['quiz']; 
					$mid = (int)$_POST['mid'];
					$final = (int)$_POST['final'];
					// Calcute the average
					$average = (int)(($quiz + $mid + $final) / 3);

					// If... else for the grade
					if ($average >= 90) { 
						$grade = "A"; 
					} else if ($average >= 80  && $average < 90) { 
						$grade
						= "B"; 
					} else if ($average >= 70 && $average <80) { 
						$grade = "C"; 
					} else if ($average >=60 && $average <70) { 
						$grade = "D"; 
					} else if ($average < 60) { 
						$grade = "F"; } 
						else { 
							$grade = "Error"; 
						}

					// This line keep the collapse after submitting
						echo "<script>document.getElementById('question1').classList.add('show');</script>";

					} ?>

					<form class="text-center" method="post"> <label
						for="quiz">Quiz score (%):</label> <input
						type="number" name="quiz" id="quiz" min="0" max="100">

						<br> <br>

						<label for="mid">Mid-Term (%):</label> <input
						type="number" name="mid" id="mid" min="0" max="100">

						<br> <br>

						<label for="final">Final (%):</label> <input
						type="number" name="final" id="final" min="0" max="100">

						<br> <br>

						<input type="submit" name="submit1" value="Calculate"> 
						<br><br><br>


						<!-- Average -->
						<input type="text" id="average" name="average" value="<?php echo isset($average) ? $average . "%" : 'Average'; ?>" readonly>


						<!-- Grade -->
						<input type="text" id="grade" name="grade" value="<?php echo
						isset($grade) ? $grade : 'Grade'; ?>" readonly>

						<br> <br>

						<!-- Reset -->
						<button type="button" id="reset1">Reset</button>

					</form> 
				</div> 
			</div>



		<!-- ******************************************************************************************************** ******************************** QUESTION 2 - REVENUE GENERATED BY SALE   ********************************
			****************************************************************************************************** -->

			<h2 class="mb-5 pb-2 w-100" style="background-color: #370617; color: white;"
			data-bs-toggle="collapse" href="#question2" role="button"
			aria-expanded="false" aria-controls="question2">Question 2
			<br> <span style="font-size: 24px;">Revenue Generated by sale</span></h2>

			<div class="container"> <div class="collapse p-4 my-4" id="question2">

				<?php
				if (isset($_POST['submit2'])) { 
					$unitPrice = (float)$_POST['unitPrice']; 
					$unitQuant = (int)$_POST['unitQuant']; 

					// Calcute the totalPrice
					$totalPrice = (float)($unitPrice * $unitQuant);

					// Discount rate (%)
					if ($unitQuant < 100) {
						$discountPercent = 0;
					} else if ($unitQuant >= 100 && $unitQuant <= 120) {
						$discountPercent = 10;
					} else if ($unitQuant > 120) {
						$discountPercent = 15;
					} else {
						$discountPercent = "Error";
					}

					// Discount amount ($)
					$discountPrice = (($discountPercent)/100) * $totalPrice;


					// Final price
					$finalPrice = $totalPrice - $discountPrice;

					// This line keep the collapse after submitting
					echo "<script>document.getElementById('question2').classList.add('show');</script>";

				} ?>
				<h4>Discounts</h4>
				<ul>
					<li>No discount is applied for a quantity of less than 100 units.</li>
					<li>A 10% discount is applied for a quantity of 100 to 120 units (inclusive).</li>
					<li>A 15% discount is applied for a quantity greater than 120 units.</li>
				</ul>
				<!-- Price -->
				<form class="text-center" method="post"> <label
					for="unitPrice">Unit price ($):</label> <input
					type="number" name="unitPrice" id="unitPrice" min="0" max="99999" step="0.01">

					<br> <br>
					<!-- Quantity -->
					<label for="unitQuant">Unit quantity:</label> <input
					type="number" name="unitQuant" id="unitQuant" min="0" max="9999">

					<br> <br> 


					<input type="submit" name="submit2" value="Calculate"> 
					<br><br><br>


					<h4>Results</h4>
					<!-- Total price -->
					<label for="totalPrice">Total price:</label>
					<input type="text" id="totalPrice" name="totalPrice" value="<?php echo isset($totalPrice) ? $totalPrice . "$" : ''; ?>" readonly>
					<br><br>


					<!-- Discount % -->
					<label for="discountPercent">Discount (%):</label>
					<input type="text" id="discountPercent" name="discountPercent" value="<?php echo
					isset($discountPercent) ? $discountPercent . "%" : ''; ?>" readonly>
					
					<br><br>

					<!-- Discount $ -->
					<label for="discountPrice">Discount ($):</label>
					<input type="text" id="discountPrice" name="discountPrice" step="0.01" value="<?php echo
					isset($discountPrice) ? $discountPrice . "$" : ''; ?>" readonly>
					
					<br><br>

					<!-- Final price -->
					<label for="finalPrice">Final Price:</label>
					<input type="text" id="finalPrice" name="finalPrice" value="<?php echo
					isset($finalPrice) ? $finalPrice . "$" : ''; ?>" readonly>
					
					<br><br>


					<!-- Reset -->
					<button type="button" id="reset2">Reset</button>

				</form> 
			</div> 
		</div>



	<!-- ******************************************************************************************************** ********************************      QUESTION 3 - AUTOMOBILE INSURANCE *************************************
		************************************************************************************************************* -->

		<h2 class="mb-5 pb-2 w-100" style="background-color: #6A040F; color: white;"
		data-bs-toggle="collapse" href="#question3" role="button"
		aria-expanded="false" aria-controls="question3">Question 3
		<br> <span style="font-size: 24px;">Automobile insurance</span></h2>

		<div class="container"> <div class="collapse p-4 my-4" id="question3">

			<?php
			if (isset($_POST['submit3'])) { 
				$age = (int)$_POST['age']; 
				$carAccident = (int)$_POST['carAccident']; 

				// Base rate
				$baseRate = 500;

				// Age surcharge
				if ($age >=18 && $age <25) {
					$ageSurcharge = 25;
				} else {
					$ageSurcharge = 0;
				}

				// Accident surcharge
				if ($carAccident == 0) {
					$accidentSurcharge = 0;
				} else if ($carAccident == 1) {
					$accidentSurcharge = 25;
				} else if ($carAccident == 2) {
					$accidentSurcharge = 25;
				} else if ($carAccident == 3) {
					$accidentSurcharge = 75;
				} else if ($carAccident == 4) {
					$accidentSurcharge = 75;
				} else if ($carAccident == 5) {
					$accidentSurcharge = 100;
				} else if ($carAccident >= 6) {
					$accidentSurcharge = "No insurance";
					$finalPriceInsurance = "No insurance";
				}

				// Final price
				if ($carAccident < 6) {
					$finalPriceInsurance = $baseRate + $ageSurcharge + $accidentSurcharge;
				}

				// This line keep the collapse after submitting
				echo "<script>document.getElementById('question3').classList.add('show');</script>";

			} ?>

			<h4>Insurance</h4>
			<ul>
				<li>Base rate = 500$</li>
				<li>Under 25 years old: $25 surcharge</li>
				<li>1 accident: $25 surcharge</li>
				<li>2 accidents: $25 surcharge</li>
				<li>3 accidents: $75 surcharge</li>
				<li>4 accidents: $75 surcharge</li>
				<li>5 accidents: $100 surcharge</li>
				<li>6 or more accidents: No insurance</li>
			</ul>
			<!-- Age -->
			<form class="text-center" method="post"> <label
				for="age">Age:</label> <input
				type="number" name="age" id="age" min="18" max="85" >

				<br> <br>
				<!-- Quantity -->
				<label for="carAccident">Car accident:</label> <input
				type="number" name="carAccident" id="carAccident" min="0" max="99">

				<br> <br> <br>


				<input type="submit" name="submit3" value="Calculate"> <br><br>


				<h4>Results</h4>
				<!-- Base Rate -->
				<label for="baseRate">Base rate:</label>
				<input type="text" id="baseRate" name="baseRate" value="<?php echo isset($baseRate) ? $baseRate . "$" : '500$'; ?>" readonly>
				<br><br>


				<!-- Age surcharge -->
				<label for="ageSurcharge">Age surcharge:</label>
				<input type="text" id="ageSurcharge" name="ageSurcharge" value="<?php echo
				isset($ageSurcharge) ? $ageSurcharge . "$"  : ''; ?>" readonly>
				<br><br>

				<!-- Accident surcharge-->
				<label for="accidentSurcharge">Accident surcharge:</label>
				<input type="text" id="accidentSurcharge" name="accidentSurcharge" step="0.01" value="<?php echo
				isset($accidentSurcharge) ? $accidentSurcharge . "$" : ''; ?>" readonly>
				<br><br>

				<!-- Final price -->
				<label for="finalPriceInsurance">Final Price:</label>
				<input type="text" id="finalPriceInsurance" name="finalPriceInsurance" value="<?php echo
				isset($finalPriceInsurance) ? $finalPriceInsurance . "$" : ''; ?>" readonly>

				<br><br>

				<!-- Reset -->
				<button id="reset3">Reset</button>

			</form>
		</div> 
	</div>




	<!-- ******************************************************************************************************** ********************************      QUESTION 4 - NUMBERS, SUM AN AVERAGE **********************************
		************************************************************************************************************* -->
		<h2 class="mb-5 pb-2 w-100" style="background-color: #9D0308; color: white;" data-bs-toggle="collapse" href="#question4" role="button" aria-expanded="false" aria-controls="question4">
			Question 4
			<br> <span style="font-size: 24px;">Sum and Average of Numbers</span>
		</h2>

		<div class="container">
			<div class="collapse p-4 my-4" id="question4">

				<?php
				if (isset($_POST['submit4'])) {
					$number1 = (int)$_POST['number1'];
					$number2 = (int)$_POST['number2'];

            // Calculate the sum and average of numbers between number1 and number2
					$sum = 0;
					$count = 0;
					$numbersString = '';
					for ($i = $number1; $i <= $number2; $i++) {
						$sum += $i;
						$count++;
						$numbersString .= $i . ', ';
					}
					$averageQ4 = $sum / $count;


            // Keep the collapse open after submitting
					echo "<script>document.getElementById('question4').classList.add('show');</script>";
				}
				?>

				<h4>Calculate the Sum and Average</h4>

				<!-- Input Form -->
				<form class="text-center" method="post">
					<label for="number1">Number 1:</label>
					<input type="number" name="number1" id="number1">
					<br><br>

					<label for="number2">Number 2:</label>
					<input type="number" name="number2" id="number2">
					<br><br><br>

					<input type="submit" name="submit4" value="Calculate">
					<br><br>

					<h4>Results</h4>

					<!-- Numbers -->
					<label for="numbers">Numbers:</label>
					<input type="text" id="numbers" name="numbers" value="<?php echo isset($numbersString) ? $numbersString : ''; ?>" readonly style="width: 50%;">
					<br><br>

					<!-- Sum -->
					<label for="sum">Sum:</label>
					<input type="text" id="sum" name="sum" value="<?php echo isset($sum) ? $sum : ''; ?>" readonly>
					<br><br>

					<!-- Average -->
					<label for="average">Average:</label>
					<input type="text" id="averageQ4" name="averageQ4" value="<?php echo isset($averageQ4) ? $averageQ4 : ''; ?>" readonly>
					<br><br>

					<!-- Reset -->
					<button type="button" id="reset4">Reset</button>

				</form>
			</div>
		</div>





	<!-- ******************************************************************************************************** ********************************      QUESTION 5 - CHECKERBOARD *********************************************
		************************************************************************************************************* -->
		<h2 class="mb-5 pb-2 w-100" style="background-color: #D00000; color: white;" data-bs-toggle="collapse" href="#question5" role="button" aria-expanded="false" aria-controls="question5">
			Question 5
			<br> <span style="font-size: 24px;">Checkerboard Pattern</span>
		</h2>

		<div class="container">
			<div class="collapse p-4 my-4" id="question5">

				<?php
				$checkerboard = '';
				if (isset($_POST['submit5'])) {
					$n = (int)$_POST['dimension'];

					// Generate the checkerboard pattern
					for ($i = 0; $i < $n; $i++) {
  						// Space fo odd lines 
						if ($i % 2 != 0) {
							$checkerboard .= '  ';
						}

   						 // Add n "#" characters per line
						for ($j = 0; $j < $n; $j++) {
							$checkerboard .= '#  ';
						}

  						// Add a line break at the end of each line
						$checkerboard .= '<br>';
					}


            // Keep the collapse open after submitting
					echo "<script>document.getElementById('question5').classList.add('show');</script>";
				}
				?>

				<h4>Generate Checkerboard Pattern</h4>

				<!-- Input Form -->
				<form class="text-center" method="post">
					<label for="dimension">Dimension (n):</label>
					<input type="number" name="dimension" id="dimension" min="0" max="20">
					<br><br>

					<input type="submit" name="submit5" value="Generate">
					<br><br>

					<h4>Checkerboard Pattern</h4>

					<!-- Checkerboard -->
					<!-- By default, HTML collapses multiple spaces into a single space and doesn't honor newline characters.  -->
					<div style="font-family: monospace; white-space: pre;"><?php echo $checkerboard; ?></div>

				</form>
			</div>
		</div>




	<!-- ******************************************************************************************************** ********************************      QUESTION 6 - CozaLozaWoza *********************************************
		************************************************************************************************************* -->
 <h2 class="mb-5 pb-2 w-100" style="background-color: #DC2F02; color: white;" data-bs-toggle="collapse" href="#question6" role="button" aria-expanded="false" aria-controls="question6">
        Question 6
        <br> <span style="font-size: 24px;">CozaLozaWoza</span>
    </h2>

    <div class="container">
        <div class="collapse p-4 my-4" id="question6">

            <?php
            $cozaLozaWozaOutput = '';
            if (isset($_POST['submit6'])) {

                // Generate the CozaLozaWoza pattern
                for ($i = 1; $i <= 110; $i++) {
                	// Initially, the output is empty
                    $output = '';
                    if ($i % 3 == 0) $output .= "Coza";
                    if ($i % 5 == 0) $output .= "Loza";
                    if ($i % 7 == 0) $output .= "Woza";
                    // If the number is not a multiple of 3, 5 or 7 (so $input = ' '), print i (the number in the loop)
                    if ($output === '') $output = $i;
                    $cozaLozaWozaOutput .= $output . ' ';

                    // Changine line every 11 numbers
                    if ($i % 11 == 0) $cozaLozaWozaOutput .= '<br>';
                }

                // Keep the collapse open after submitting
                echo "<script>document.getElementById('question6').classList.add('show');</script>";
            }
            ?>

            <h4>Generate CozaLozaWoza Pattern</h4>

            <!-- Input Form -->
            <form class="text-center" method="post">
                <input type="submit" name="submit6" value="Generate">
                <br><br>

                

                <!-- CozaLozaWoza Output -->
                <div style="font-family: monospace; white-space: pre;"><?php echo $cozaLozaWozaOutput; ?></div>
            </form>
        </div>
    </div>



	<!-- ******************************************************************************************************** ********************************      QUESTION 7 - NUMBERS, SUM AND AVERAGE  *********************************
		************************************************************************************************************* -->
	  <h2 class="mb-5 pb-2 w-100" style="background-color: #E85D04; color: white;" data-bs-toggle="collapse" href="#question7" role="button" aria-expanded="false" aria-controls="question7">
        Question 7
        <br> <span style="font-size: 24px;">Even Numbers Display</span>
    </h2>

    <div class="container">
        <div class="collapse p-4 my-4" id="question7">

            <?php
            $evenNumbersOutput = '';
            if (isset($_POST['submit7'])) {

                // Mimic a for loop using a while loop
                $i = 0;
                while ($i <= 100) {
                	// For displaying reasons. Changing line every 20.
                	if ($i % 20 == 0) {
                		$evenNumbersOutput .= "<br>";
                	}
                    if ($i % 2 == 0) {
                        $evenNumbersOutput .= $i . ' ';
                    }
                    $i++;
                }

                // Keep the collapse open after submitting
                echo "<script>document.getElementById('question7').classList.add('show');</script>";
            }
            ?>

            <h4>Display Even Numbers from 0 to 100</h4>

            <!-- Input Form -->
            <form class="text-center" method="post">
                <input type="submit" name="submit7" value="Display">
                <br><br>

                <h4>Even Numbers</h4>

                <!-- Even Numbers Output -->
                <div style="font-family: monospace; white-space: pre;"><?php echo $evenNumbersOutput; ?></div>
            </form>
        </div>
    </div>


	<!-- ******************************************************************************************************** ********************************      QUESTION 8 - COUNT & DISPLAY THE VOWEL  *********************************
		************************************************************************************************************* -->
		<h2 class="mb-5 pb-2 w-100" style="background-color: #F48C06; color: white;" data-bs-toggle="collapse" href="#question8" role="button" aria-expanded="false" aria-controls="question8">
			Question 8
			<br> <span style="font-size: 24px;">Count Vowels</span>
		</h2>

		<div class="container">
			<div class="collapse p-4 my-4" id="question8">
				<?php
				if (isset($_POST['submit8'])) {
					$string = $_POST['string'];
					$vowels = ['a', 'e', 'i', 'o', 'u', 'y'];
					$countQ8 = 0;

					foreach (str_split($string) as $char) {
						if (in_array(strtolower($char), $vowels)) {
							$countQ8++;
						}
					}

			// Keep the collapse open after submitting
					echo "<script>document.getElementById('question8').classList.add('show');</script>";
				}
				?>

				<!-- Input Form -->
				<form class="text-center" method="post">
					<label for="string">Input String:</label>
					<input type="text" name="string" id="string">
					<br><br>

					<input type="submit" name="submit8" value="Count">
					<br><br>

					<h4>Result</h4>

					<!-- Count -->
					<label for="countQ8">Vowel Count:</label>
					<input type="text" id="countQ8" name="countQ8" value="<?php echo isset($countQ8) ? $countQ8 : ''; ?>" readonly>
					<br><br>

					<!-- Reset -->
					<button type="button" id="reset8">Reset</button>
				</form>
			</div>
		</div>


	<!-- ******************************************************************************************************** ********************************      QUESTION 9 - MULTIPLICATION TABLE  *********************************
		************************************************************************************************************* -->

		<h2 class="mb-5 pb-2 w-100" style="background-color: #FAA307; color: white;" data-bs-toggle="collapse" href="#question9" role="button" aria-expanded="false" aria-controls="question9">
			Question 9
			<br> <span style="font-size: 24px;">Multiplication Table</span>
		</h2>

		<div class="container">
			<div class="collapse p-4 my-4" id="question9">
				<?php
				if (isset($_POST['submit9'])) {
					$rows = (int)$_POST['rows'];
					if ($rows > 0) {
				// Keep the collapse open after submitting
						echo "<script>document.getElementById('question9').classList.add('show');</script>";
					} else {

					}
				}
				?>

				<!-- Input Form -->
				<form class="text-center" method="post">
					<label for="rows">Number of Rows:</label>
					<input type="number" name="rows" id="rows" min="1" max="20">
					<br><br>

					<input type="submit" name="submit9" value="Generate Table">
					<br><br>

					<h4>Result</h4>

					<!-- Table -->
					<table>
						<?php
						if (isset($_POST['submit9'])) {
							for ($i = 1; $i <= $rows; $i++) {
								echo "<tr>";
								for ($j = 1; $j <= 5; $j++) {
									$result = $i * $j;
									echo "<td>{$i} * {$j} = {$result}</td>";
								}
								echo "</tr>";
							}
						}
						?>
					</table>

					<br>
					<!-- Reset -->
					<button type="button" id="reset9">Reset</button>
				</form>
			</div>
		</div>



	<!-- ******************************************************************************************************** ********************************      QUESTION 10 -  TABLE 1 TO 100  *********************************
		************************************************************************************************************* -->
		<h2 class="mb-5 pb-2 w-100" style="background-color: #FFBA08; color: white;" data-bs-toggle="collapse" href="#question10" role="button" aria-expanded="false" aria-controls="question10">
			Question 10
			<br> <span style="font-size: 24px;">Table 1 to 100</span>
		</h2>

		<div class="container">
			<div class="collapse p-4 my-4" id="question10">
				

				<!-- Input Form -->
				<!-- Add your input form code here if needed -->

				<!-- Table -->
				<table>
					<?php
					$countQ10 = 0;
					for ($i = 1; $i <= 10; $i++) {
						echo "<tr>";
						for ($j = 1; $j <= 10; $j++) {
							$countQ10++;
							$result = $countQ10;
							echo "<td>{$result}</td>";
						}
						echo "</tr>";
					}
					?>
				</table>


			</script>
		</div>
	</div>


	<script src="js/bootstrap.bundle.js"></script>
	<script src="js/jquery.js"></script>
	<script src="js/custom.js"></script>
</body>
</html>